cluster_reduce_fn: null
extrapolate: false
fn: vedb_gaze.error_computation.compute_error
lambd: 0.1
method: tps
min_pupil_confidence: 0.6
outlier_stds: null
vertical_horizontal_smooth_error_resolution:
- 300
- 400
