aspect_ratio_keep: less_than_threshold
aspect_ratio_threshold: 1.75
aspect_ratio_type: max/min
bimodal_std_threshold: 2.5
do_duration_pre_check: True
duration_threshold: 0.3
fn: vedb_gaze.marker_parsing.filter_and_split
max_epoch_gap: 15
max_epoch_length: 150
max_marker_movement: null
min_cluster_time: 0.3
min_epoch_length: 15
size_std_threshold: null
