aspect_ratio_keep: less_than_threshold
aspect_ratio_threshold: 1.75
aspect_ratio_type: max/min
bimodal_std_threshold: 2.5
cluster_by:
- marker:timestamp
- marker:norm_pos
cluster_kw: null
cluster_method: DBSCAN
cut_cluster_outliers: true
do_duration_pre_check: true
duration_threshold: 0.3
fn: vedb_gaze.marker_parsing.filter_and_cluster
max_cluster_std: 4.0
max_cluster_time: 300
max_marker_movement: 0.1
min_cluster_time: 0.3
min_n_clusters: 5
